-- Migration 029: Publish MessageStore with verification proof
-- Generated by eh-publish.py on 2026-03-09 12:05
-- Bytecode verified: unknown, optimizer=OFF

UPDATE contracts SET
  short_description = 'On-chain message storage contract from day 10 of Ethereum',
  description = 'One of Ethereum''s earliest smart contracts, deployed on August 7, 2015 — just 10 days after mainnet launch (block 53,573). A minimal contract that stores a single string message on-chain, with a public getter and a set() function allowing anyone to overwrite it. Deployed by 0x8674c218, who deployed 18 contracts in August 2015 alone, making them one of the most prolific early Ethereum experimenters. The contract represents the "hello world" era of smart contract development — developers testing what was possible on this new platform.
',
  contract_type = 'utility',
  featured = FALSE,
  source_code = 'contract MessageStore {
  string public message;
  function set(string _message) {
    message = _message;
  }
}
',
  compiler_language = 'solidity',
  compiler_commit = '6ff4cd6',
  compiler_repo = 'ethereum/solidity',
  verification_method = 'exact_bytecode_match',
  verification_notes = 'Bytecode verified with native C++ solc v0.1.1 (webthree-umbrella), optimizer ON.
Selectors identified via calldata forensics: set(string) = 0x4ed3885e, message() = 0xe21f37ce.
Qwen batch triage initially misidentified this as a mapping-based contract with tx.origin access control — fully incorrect. Actual contract is a simple string storage with no access control.
',
  historical_significance = 'One of the earliest smart contracts on Ethereum mainnet, representing the experimental spirit of Frontier''s first days.',
  historical_context = 'Frontier era — day 10 of Ethereum. Developers were still exploring what smart contracts could do.',
  manual_categories = '["messaging", "frontier-experiment"]'::jsonb,
  updated_at = NOW()
WHERE address = '0xd2ec98c4459edab3df7fa28c67b40f15c42b7614';
-- NOTE: INSERT removed. This address is an EOA (wallet), not a contract.
-- The real MessageStore is 0xd2eccde805e888ae37646544d60185b842ff3d6b.
-- See migration 032 which cleans up the erroneous entry.
