-- Migration 041: Update Doge-ETH bounty contract with correct history

UPDATE contracts SET
  etherscan_contract_name = 'Doge-ETH Bounty Fund',
  short_description = 'The Ethereum Foundation Doge-ETH bridge bounty fund, routing over 5,400 ETH through on-chain governance from 2015 to 2018.',
  description = 'The Ethereum Foundation Doge-ETH bridge bounty fund, governed on-chain using the ethereum.org Blockchain Congress contract. Deployed by Vitalik Buterin on December 28, 2015, the contract was seeded with 100 ETH on December 31 and received over 5,400 ETH in total (including two large deposits of 500 ETH and 4,500 ETH on January 19-20, 2016). It funded development of the Dogecoin-Ethereum bridge over two years, with bounty payouts voted on by a small group of EF developers including Vitalik (0xd1220a0c), EF 1 (0x5ed8cee6), and the EF presale address (0xd3cda913). Governance continued through February 2018, with Alex Van de Sande (@avsa) publicly discussing the bounty. The underlying contract is the ethereum.org Blockchain Congress tutorial source code.',
  historical_significance = 'One of the largest on-chain governance experiments in early Ethereum history, routing over 5,400 ETH through a democratic voting contract to fund a cross-chain bridge. The contract demonstrates the EF using its own governance tooling in production: the ethereum.org Congress tutorial became the actual treasury for a multi-year funded development program. A direct ancestor of the decentralized grant programs that proliferated across the Ethereum ecosystem in later years.',
  historical_context = 'In late 2015, the Ethereum Foundation was exploring Dogecoin as a friendly first cross-chain bridge candidate. Vitalik deployed the Congress contract the same day the ethereum.org tutorial describing it was updated, then immediately used it as a real treasury. Major ETH deposits in January 2016 (500 ETH and 4,500 ETH) funded the bridge development bounty. The EF presale address (0xd3cda913deb6f0967b6c3174c2bccddb531d0f4e) was one of the voters, confirming this was an official EF program. Ownership was transferred in July 2017 as the project matured. Alex Van de Sande (@avsa) tweeted about the bounty in February 2018 as work approached completion. The bridge work funded here eventually became the dogethereum project.'
WHERE address = '0xdbf03b407c01e7cd3cbea99509d93f8dddc8c6fb';
