-- Migration 042: Full history for Doge-ETH Bounty DAO from Julian's research thread

UPDATE contracts SET
  etherscan_contract_name = 'Doge-ETH Bounty DAO',
  short_description = 'The Doge-Ethereum Bounty DAO created by avsa on Dec 28, 2015. Funded over 5,400 ETH in bridge development, holds 50,000 MistCoin. Active 2015-2021.',
  description = 'The Doge-Ethereum Bounty DAO, created by Alex Van de Sande (@avsa) on December 28, 2015. A governance contract with 8 members including Vitalik Buterin, Piper Merriam, Hudson Jameson, J. Ross Nicoll (Dogecoin developer), George Hallam, Max (Dogecoin), and Ming Chan, each with voting rights on proposals. Requires at least 5 votes and 3 approvals to pass. The DAO funded development of the Dogecoin-Ethereum bridge over several years, disbursing ETH to teams including Trubit and CoinFabrik for successfully sending Doge to the Ethereum Rinkeby testnet. It also holds 50,000 MistCoin ($WMC), the first ERC-20 compliant token, sent via Proposal 2. The underlying contract is the ethereum.org Blockchain Congress tutorial source code compiled with Solidity 0.1.6.',
  historical_significance = 'A landmark early DAO, one of the first on-chain governance structures used for a real multi-year funded development program. The DAO bridged the Ethereum and Dogecoin communities, funded by over 5,400 ETH in contributions. It holds 50,000 MistCoin ($WMC), the first ERC-20 compliant token ever deployed (November 3, 2015). Proposal 7 returned 5,000 ETH to an unsatisfied Genesis wallet holder. The DAO was active from 2015 to 2021, when it transitioned to a Gnosis Safe. The work it funded contributed to Wrapped Doge becoming a reality.',
  historical_context = 'Alex Van de Sande, head of the Mist wallet and a pioneer in ERC-20, DAOs, ENS, and NFTs, deployed this contract the same day the ethereum.org DAO tutorial was updated. He seeded it with 100 ETH to test it, later returned via Proposal 1. The first substantive proposals sent 50,000 MistCoin to avsa (Proposal 2, passed) and awarded bridge development bounties to Trubit, CoinFabrik, and Oscar for achieving Doge-to-Ethereum test transfers on Rinkeby. A 5,000 ETH deposit from a Genesis wallet was refunded after the donor withdrew. Governance continued with a 2021 migration to Gnosis Safe. Members: avsa, Vitalik Buterin (2 votes), Ming Chan, Piper Merriam, Hudson Jameson, J. Ross Nicoll, George Hallam, Max (Dogecoin).'
WHERE address = '0xdbf03b407c01e7cd3cbea99509d93f8dddc8c6fb';
