-- Migration 043: MistCoin history + fix Doge-ETH DAO MistCoin claim

-- Fix Doge-ETH DAO description: MistCoin is not "first ERC-20" but prototype
UPDATE contracts SET
  description = 'The Doge-Ethereum Bounty DAO, created by Alex Van de Sande (@avsa) on December 28, 2015. A governance contract with 8 members including Vitalik Buterin, Piper Merriam, Hudson Jameson, J. Ross Nicoll (Dogecoin developer), George Hallam, Max (Dogecoin), and Ming Chan, each with voting rights on proposals. Requires at least 5 votes and 3 approvals to pass. The DAO funded development of the Dogecoin-Ethereum bridge over several years, disbursing ETH to teams including Trubit and CoinFabrik for successfully sending Doge to the Ethereum Rinkeby testnet. It also holds 50,000 MistCoin ($WMC), the token Fabian Vogelsteller deployed on November 3, 2015 to prototype what became the ERC-20 standard. MistCoin predates ERC-20 by 16 days and does not implement the full standard, but it is the token that directly inspired it. The underlying contract is the ethereum.org Blockchain Congress tutorial source code compiled with Solidity 0.1.6.'
WHERE address = '0xdbf03b407c01e7cd3cbea99509d93f8dddc8c6fb';

-- Add MistCoin history
UPDATE contracts SET
  short_description = 'The prototype token that inspired ERC-20, deployed by Fabian Vogelsteller on November 3, 2015, sixteen days before he submitted the ERC-20 proposal.',
  description = 'MistCoin, deployed by Fabian Vogelsteller on November 3, 2015 as a test token while developing the concept that became ERC-20. The contract implements transfer and balanceOf but not transferFrom, approve, allowance, or totalSupply. Fabian submitted ERC-20 (Issue #20) to the ethereum/EIPs repo on November 19, 2015, sixteen days after deploying this contract. MistCoin is therefore not compliant with the ERC-20 standard even as originally proposed, but it is the prototype token that directly inspired and preceded it.',
  historical_significance = 'The token that preceded and inspired ERC-20. Fabian Vogelsteller, author of ERC-20, deployed MistCoin as a test implementation 16 days before submitting the ERC-20 draft proposal. While often called the first ERC-20 token, it technically does not implement the full standard: it is missing transferFrom, approve, allowance, and totalSupply. The historically accurate claim is that it is the prototype that inspired ERC-20, not a compliant implementation of it.',
  historical_context = 'In November 2015, Fabian Vogelsteller was working on the Mist wallet and experimenting with token contract interfaces. He deployed MistCoin at block 483,325 on November 3, 2015, gave tokens away on Reddit, and used it to test token handling in Mist. On November 19, 2015, he submitted ERC-20 as Issue #20 in the ethereum/EIPs repository, with the full interface including transferFrom, approve, and allowance. avsa noted that since Fabian had just written the spec, MistCoin became the first token deployed against the evolving standard concept. The token was later sent in bulk to the Doge-ETH Bounty DAO, which still holds 50,000 MistCoin.'
WHERE address = '0xf4eced2f682ce333f96f2d8966c613ded8fc95dd';
