-- Migration 056: Add source code, ABI, and history to CryptoCats test contracts

-- T1: 0xD23AdE68C693264Aa9e8f8303F912A3E54718456
UPDATE contracts SET
  description = 'Deployed one day before the public CryptoCats launch on 2017-11-12, this test contract introduced the catName string field in the Offer struct, baking "Cat 0" through "Cat 11" directly into the blockchain. Unlike the production v3 contract (0x088C), this version has only 18 functions with no marketplace functions yet. The struct follows v3 field order: {bool isForSale; uint catIndex; address seller; string catName}. Compiled with Solidity 0.4.18 + optimizer. Source reconstructed by EthereumHistory.com achieved 98.1% match (5715/5823 bytes). The 108-byte gap is dead code from the constructor-only cat initialization function.',
  historical_context = 'CryptoCats was created by ThetwentySix (Nas Munawar, Gendry Morales, Jochy Reyes) in November 2017, inspired by CryptoPunks. Two test contracts were deployed on November 11, one day before the public launch on November 12. These test contracts show the evolution from a simple "claim cats by index" model to the full marketplace with pricing, buying, and selling. The test contracts introduced cat names as on-chain strings and the allInitialOwnersAssigned() initialization pattern. The production v3 contract (0x088C6Ad962812b5Aa905BA6F3c5c145f9D4C079f) was verified on Etherscan with Solidity 0.4.19.'
WHERE address = '0xD23AdE68C693264Aa9e8f8303F912A3E54718456';

-- T2: 0x78eea094e1d30141ccade64f8d29a7bfcc921f9e
UPDATE contracts SET
  description = 'Second pre-launch test contract for CryptoCats, deployed the same day as T1. Notable differences: compiled without optimizer (8451 bytes vs T1''s 5823), seller initialized to zero address (vs msg.sender in T1), and imageHash set to placeholder "INSERT ACTUAL HASH HERE" rather than the actual image hash. The struct and function signatures are identical to T1. At runtime, allInitialOwnersAssigned() only sets allCatsAssigned=true; the actual cat initialization is dead code from the constructor. Source reconstructed by EthereumHistory.com achieved 96.3% match (8137/8451 bytes). Same 314-byte gap from dead constructor code.',
  historical_context = 'CryptoCats was created by ThetwentySix (Nas Munawar, Gendry Morales, Jochy Reyes) in November 2017, inspired by CryptoPunks. Two test contracts were deployed on November 11, one day before the public launch on November 12. This second test (T2) was likely an iteration on T1, compiled without the optimizer to debug behavior. The placeholder imageHash ("INSERT ACTUAL HASH HERE") suggests the developer had not yet finalized the cat image set. Both test contracts deployed from the same address (0x0003b2f7218896285a88a1c6b97f8ae692036edb).'
WHERE address = '0x78eea094e1d30141ccade64f8d29a7bfcc921f9e';
