/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  EthereumHistory,
  EthereumHistoryInterface,
} from "../EthereumHistory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "contentJson",
        type: "string",
      },
    ],
    name: "HistoryPublished",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "getHistoryHash",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
    ],
    name: "hasHistory",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "historyHashes",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "contentHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "contentJson",
        type: "string",
      },
    ],
    name: "publishHistory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610356806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80637a265bd2146100515780637e1960f014610066578063bab8894114610099578063e2bee1df146100d4575b600080fd5b61006461005f366004610241565b6100fd565b005b6100866100743660046102c8565b60006020819052908152604090205481565b6040519081526020015b60405180910390f35b6100c46100a73660046102c8565b6001600160a01b0316600090815260208190526040902054151590565b6040519015158152602001610090565b6100866100e23660046102c8565b6001600160a01b031660009081526020819052604090205490565b6001600160a01b03841661016a5760405162461bcd60e51b815260206004820152602960248201527f457468657265756d486973746f72793a20696e76616c696420636f6e7472616360448201526874206164647265737360b81b60648201526084015b60405180910390fd5b826101c55760405162461bcd60e51b815260206004820152602560248201527f457468657265756d486973746f72793a20696e76616c696420636f6e74656e74604482015264040d0c2e6d60db1b6064820152608401610161565b6001600160a01b03841660008181526020819052604090819020859055518491907f71a3e348ed31b3ad2702e976a3718b719d1fd54c6867b0e4d86a715e3e9e638190610217904290879087906102ea565b60405180910390a350505050565b80356001600160a01b038116811461023c57600080fd5b919050565b6000806000806060858703121561025757600080fd5b61026085610225565b935060208501359250604085013567ffffffffffffffff8082111561028457600080fd5b818701915087601f83011261029857600080fd5b8135818111156102a757600080fd5b8860208285010111156102b957600080fd5b95989497505060200194505050565b6000602082840312156102da57600080fd5b6102e382610225565b9392505050565b83815260406020820152816040820152818360608301376000818301606090810191909152601f909201601f191601019291505056fea26469706673582212208de42a736d62f13941b71d440b14894bb53e884b8bdf0c07822097f02dda1d6564736f6c63430008140033";

type EthereumHistoryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EthereumHistoryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EthereumHistory__factory extends ContractFactory {
  constructor(...args: EthereumHistoryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EthereumHistory & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EthereumHistory__factory {
    return super.connect(runner) as EthereumHistory__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EthereumHistoryInterface {
    return new Interface(_abi) as EthereumHistoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EthereumHistory {
    return new Contract(address, _abi, runner) as unknown as EthereumHistory;
  }
}
