"use client";

import { useState, useMemo } from "react";
import { Copy, Check, Search, ChevronDown, ChevronUp, Code, AlertCircle, Info } from "lucide-react";
import { copyToClipboard } from "@/lib/utils";

interface DecompiledCodeViewerProps {
  decompiledCode: string | null;
  decompilationSuccess: boolean;
  bytecode?: string | null;
}

interface ParsedFunction {
  name: string;
  signature: string;
  body: string;
  isPayable: boolean;
  lineStart: number;
}

type CodeFormat = "python" | "solidity";

/**
 * Detect whether the decompiled code is Python-style (Panoramix) or
 * Solidity-style (SEVM's solidify()).
 */
function detectCodeFormat(code: string): CodeFormat {
  const trimmed = code.trim();
  // SEVM output starts with // comments and uses "contract Contract {"
  if (
    trimmed.startsWith("//") ||
    /\bcontract\s+\w+\s*\{/.test(trimmed) ||
    /\bfunction\s+\w*\s*\(/.test(trimmed)
  ) {
    return "solidity";
  }
  return "python";
}

/**
 * Check if the decompiled code was auto-generated by our on-the-fly decompiler.
 */
function isAutoDecompiled(code: string): boolean {
  return code.includes("Decompiled by ethereumhistory.com");
}

// ---------------------------------------------------------------------------
// Python-style parser (Panoramix "def funcName():" format)
// ---------------------------------------------------------------------------

function parsePythonDecompiledCode(code: string): {
  storage: string[];
  functions: ParsedFunction[];
  header: string;
} {
  const lines = code.split("\n");
  const storage: string[] = [];
  const functions: ParsedFunction[] = [];
  let header = "";

  let currentFunction: Partial<ParsedFunction> | null = null;
  let functionLines: string[] = [];
  let inStorage = false;
  let headerDone = false;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Detect header (comments and blank lines before any def)
    if (!headerDone && !trimmed.startsWith("def ") && (trimmed.startsWith("#") || trimmed === "")) {
      header += line + "\n";
      continue;
    }
    headerDone = true;

    // Detect storage section
    if (trimmed === "def storage:" || trimmed.startsWith("def storage:")) {
      inStorage = true;
      continue;
    }

    // Storage variables (indented lines under def storage:)
    if (inStorage) {
      // Blank line or section comment ends storage section
      if (trimmed === "" || (trimmed.startsWith("#") && !trimmed.startsWith("# "))) {
        inStorage = false;
        // fall through to handle this line normally
      } else if (trimmed.startsWith("def ")) {
        inStorage = false;
        // fall through to function detection below
      } else {
        // Storage variable line (including # comments within storage)
        if (trimmed.startsWith("#")) {
          // Section comment within storage — skip
        } else {
          storage.push(trimmed);
        }
        continue;
      }
    }

    // Section comments like "# Regular functions" — skip but end storage
    if (trimmed.startsWith("#")) {
      // If we're building a function body and the next non-blank line is a def,
      // this is a section separator. Include it in function body for context.
      if (currentFunction) {
        functionLines.push(line);
      }
      continue;
    }

    // Blank lines
    if (trimmed === "") {
      if (currentFunction) {
        functionLines.push(line);
      }
      continue;
    }

    // New function definition
    if (trimmed.startsWith("def ")) {
      // Save previous function if exists
      if (currentFunction && currentFunction.name) {
        functions.push({
          name: currentFunction.name,
          signature: currentFunction.signature || "",
          body: functionLines.join("\n"),
          isPayable: currentFunction.isPayable || false,
          lineStart: currentFunction.lineStart || 0,
        });
      }

      const isPayable = trimmed.includes("payable");

      // Extract function name and signature
      // Handles: def funcName(params), def funcName(?), def _fallback(?) payable:
      const match = trimmed.match(/def\s+([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(([^)]*)\)/);
      if (match) {
        currentFunction = {
          name: match[1],
          signature: `${match[1]}(${match[2]})`,
          isPayable,
          lineStart: i,
        };
        functionLines = [line];
      } else {
        // Fallback: try to extract just the name (handles unusual signatures)
        const nameMatch = trimmed.match(/def\s+([a-zA-Z_$][a-zA-Z0-9_$]*)/);
        if (nameMatch) {
          currentFunction = {
            name: nameMatch[1],
            signature: nameMatch[1] + "(…)",
            isPayable,
            lineStart: i,
          };
          functionLines = [line];
        } else {
          currentFunction = null;
          functionLines = [];
        }
      }
      continue;
    }

    // Continue building current function
    if (currentFunction) {
      functionLines.push(line);
    }
  }

  // Don't forget the last function
  if (currentFunction && currentFunction.name) {
    functions.push({
      name: currentFunction.name,
      signature: currentFunction.signature || "",
      body: functionLines.join("\n"),
      isPayable: currentFunction.isPayable || false,
      lineStart: currentFunction.lineStart || 0,
    });
  }

  return { storage, functions, header };
}

// ---------------------------------------------------------------------------
// Solidity-style parser (SEVM "function funcName() ..." format)
// ---------------------------------------------------------------------------

function parseSolidityDecompiledCode(code: string): {
  storage: string[];
  functions: ParsedFunction[];
  header: string;
} {
  const lines = code.split("\n");
  const storage: string[] = [];
  const functions: ParsedFunction[] = [];
  let header = "";

  // Collect header comments (// lines at the top)
  let lineIdx = 0;
  while (lineIdx < lines.length) {
    const trimmed = lines[lineIdx].trim();
    if (trimmed.startsWith("//") || trimmed === "") {
      header += lines[lineIdx] + "\n";
      lineIdx++;
    } else {
      break;
    }
  }

  // Track brace depth and current function
  let currentFunction: Partial<ParsedFunction> | null = null;
  let functionLines: string[] = [];
  let braceDepth = 0;
  let inContract = false;
  let contractBraceStart = 0;

  for (let i = lineIdx; i < lines.length; i++) {
    const line = lines[i];
    const trimmed = line.trim();

    // Track contract block
    if (!inContract && /^\s*contract\s+/.test(line)) {
      inContract = true;
      contractBraceStart = braceDepth;
      // Count braces on this line
      for (const ch of line) {
        if (ch === "{") braceDepth++;
        if (ch === "}") braceDepth--;
      }
      continue;
    }

    // Detect state variables inside contract (mapping, uint, address, etc.)
    if (
      inContract &&
      !currentFunction &&
      trimmed &&
      !trimmed.startsWith("function ") &&
      !trimmed.startsWith("event ") &&
      !trimmed.startsWith("modifier ") &&
      !trimmed.startsWith("constructor") &&
      !trimmed.startsWith("fallback") &&
      !trimmed.startsWith("receive") &&
      !trimmed.startsWith("//") &&
      !trimmed.startsWith("}") &&
      !trimmed.startsWith("{") &&
      /^(mapping|uint|int|address|bool|bytes|string|struct|enum)/.test(trimmed)
    ) {
      storage.push(trimmed.replace(/;$/, ""));
      continue;
    }

    // Detect function/fallback/receive/constructor declarations
    const funcMatch = trimmed.match(
      /^(function\s+([a-zA-Z_$][a-zA-Z0-9_$]*)\s*\(([^)]*)\)|fallback\s*\(\)|receive\s*\(\)|constructor\s*\(([^)]*)\))/
    );

    if (funcMatch && inContract && !currentFunction) {
      const isPayable = trimmed.includes("payable");
      let funcName: string;
      let sig: string;

      if (trimmed.startsWith("fallback")) {
        funcName = "_fallback";
        sig = "fallback()";
      } else if (trimmed.startsWith("receive")) {
        funcName = "_receive";
        sig = "receive()";
      } else if (trimmed.startsWith("constructor")) {
        funcName = "constructor";
        sig = `constructor(${funcMatch[4] || ""})`;
      } else {
        funcName = funcMatch[2] || "unknown";
        sig = `${funcName}(${funcMatch[3] || ""})`;
      }

      currentFunction = {
        name: funcName,
        signature: sig,
        isPayable,
        lineStart: i,
      };
      functionLines = [line];

      // Count braces on this line to track function scope
      let funcBraces = 0;
      for (const ch of line) {
        if (ch === "{") funcBraces++;
        if (ch === "}") funcBraces--;
      }

      // If the function opens and closes on the same line
      if (funcBraces === 0 && line.includes("{") && line.includes("}")) {
        functions.push({
          name: currentFunction.name!,
          signature: currentFunction.signature || "",
          body: functionLines.join("\n"),
          isPayable: currentFunction.isPayable || false,
          lineStart: currentFunction.lineStart || 0,
        });
        currentFunction = null;
        functionLines = [];
      }

      // Track overall brace depth
      for (const ch of line) {
        if (ch === "{") braceDepth++;
        if (ch === "}") braceDepth--;
      }
      continue;
    }

    // If we're inside a function, accumulate lines until braces balance
    if (currentFunction) {
      functionLines.push(line);

      for (const ch of line) {
        if (ch === "{") braceDepth++;
        if (ch === "}") braceDepth--;
      }

      // When we return to the contract's brace level, the function is complete
      if (braceDepth <= contractBraceStart + 1) {
        functions.push({
          name: currentFunction.name!,
          signature: currentFunction.signature || "",
          body: functionLines.join("\n"),
          isPayable: currentFunction.isPayable || false,
          lineStart: currentFunction.lineStart || 0,
        });
        currentFunction = null;
        functionLines = [];
      }
      continue;
    }

    // Track braces for non-function lines
    for (const ch of line) {
      if (ch === "{") braceDepth++;
      if (ch === "}") braceDepth--;
    }
  }

  // Push any remaining function
  if (currentFunction && currentFunction.name) {
    functions.push({
      name: currentFunction.name,
      signature: currentFunction.signature || "",
      body: functionLines.join("\n"),
      isPayable: currentFunction.isPayable || false,
      lineStart: currentFunction.lineStart || 0,
    });
  }

  // If no functions were parsed (SEVM sometimes outputs flat code),
  // try a simpler approach: split on "function " keyword at top level
  if (functions.length === 0 && code.includes("function ")) {
    return parseSoliditySimple(code, header);
  }

  return { storage, functions, header };
}

/**
 * Fallback parser for Solidity-style code where brace-tracking doesn't work.
 * Splits on top-level "function" keywords.
 */
function parseSoliditySimple(code: string, header: string): {
  storage: string[];
  functions: ParsedFunction[];
  header: string;
} {
  const functions: ParsedFunction[] = [];
  const regex = /^[ \t]*(function\s+([a-zA-Z_$]\w*)\s*\([^)]*\)[^{]*\{)/gm;
  let match;
  const starts: { name: string; sig: string; index: number; isPayable: boolean }[] = [];

  while ((match = regex.exec(code)) !== null) {
    const isPayable = match[1].includes("payable");
    starts.push({
      name: match[2],
      sig: match[2] + "(…)",
      index: match.index,
      isPayable,
    });
  }

  for (let i = 0; i < starts.length; i++) {
    const start = starts[i];
    const end = i + 1 < starts.length ? starts[i + 1].index : code.length;
    const body = code.slice(start.index, end).trim();
    const lineStart = code.slice(0, start.index).split("\n").length - 1;

    functions.push({
      name: start.name,
      signature: start.sig,
      body,
      isPayable: start.isPayable,
      lineStart,
    });
  }

  return { storage: [], functions, header };
}

// ---------------------------------------------------------------------------
// Unified parser entry point
// ---------------------------------------------------------------------------

/**
 * Normalize escaped newlines/tabs that may have been stored literally
 * in the database (e.g. Python pipeline double-escaping).
 *
 * Detects strings that contain literal `\n` (two characters: backslash + n)
 * instead of real newline characters and converts them.
 */
function normalizeEscapedWhitespace(code: string): string {
  // If the code already has real newlines, no fixup needed
  if (code.includes("\n")) return code;
  // Replace literal \n and \t sequences with real whitespace
  return code.replace(/\\n/g, "\n").replace(/\\t/g, "\t");
}

function parseDecompiledCode(code: string): {
  storage: string[];
  functions: ParsedFunction[];
  header: string;
  format: CodeFormat;
} {
  const normalized = normalizeEscapedWhitespace(code);
  const format = detectCodeFormat(normalized);
  const result =
    format === "solidity"
      ? parseSolidityDecompiledCode(normalized)
      : parsePythonDecompiledCode(normalized);
  return { ...result, format };
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export function DecompiledCodeViewer({
  decompiledCode,
  decompilationSuccess,
  bytecode,
}: DecompiledCodeViewerProps) {
  const [copied, setCopied] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [expandedFunctions, setExpandedFunctions] = useState<Set<string>>(new Set());
  const [showAllCode, setShowAllCode] = useState(false);

  // Normalize escaped whitespace (some DB records store literal \n)
  const normalizedCode = useMemo(
    () => decompiledCode ? normalizeEscapedWhitespace(decompiledCode) : null,
    [decompiledCode]
  );

  // Parse the decompiled code
  const parsed = useMemo(() => {
    if (!normalizedCode || !decompilationSuccess) return null;
    return parseDecompiledCode(normalizedCode);
  }, [normalizedCode, decompilationSuccess]);

  const isAutoGenerated = useMemo(
    () => normalizedCode ? isAutoDecompiled(normalizedCode) : false,
    [normalizedCode]
  );

  // Filter functions by search query, preserving original indices
  const filteredFunctions = useMemo(() => {
    if (!parsed) return [];
    const indexed = parsed.functions.map((f, i) => ({ ...f, originalIndex: i }));
    if (!searchQuery.trim()) return indexed;

    const query = searchQuery.toLowerCase();
    return indexed.filter(
      (f) =>
        f.name.toLowerCase().includes(query) ||
        f.signature.toLowerCase().includes(query) ||
        f.body.toLowerCase().includes(query)
    );
  }, [parsed, searchQuery]);

  const handleCopy = async () => {
    if (!normalizedCode) return;
    const success = await copyToClipboard(normalizedCode);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const toggleFunction = (key: string) => {
    setExpandedFunctions((prev) => {
      const next = new Set(prev);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  };

  const expandAll = () => {
    if (parsed) {
      setExpandedFunctions(new Set(parsed.functions.map((f, i) => `${f.name}-${i}`)));
    }
  };

  const collapseAll = () => {
    setExpandedFunctions(new Set());
  };

  // No decompiled code available
  if (!decompiledCode) {
    return (
      <div className="rounded-xl border border-obsidian-800 p-8 text-center">
        <Code className="w-12 h-12 mx-auto mb-4 text-obsidian-600" />
        <h3 className="text-lg font-medium mb-2 text-obsidian-400">No Decompiled Code</h3>
        <p className="text-sm text-obsidian-500 max-w-md mx-auto">
          This contract&apos;s bytecode could not be decompiled. This may be because
          the bytecode is too short, uses an unsupported pattern, or is intentionally obfuscated.
        </p>
        {bytecode && (
          <p className="text-xs text-obsidian-600 mt-4">
            Bytecode length: {Math.floor(bytecode.length / 2)} bytes
          </p>
        )}
      </div>
    );
  }

  // Decompilation failed but we have some output
  if (!decompilationSuccess) {
    return (
      <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-6">
        <div className="flex items-start gap-3 mb-4">
          <AlertCircle className="w-5 h-5 text-yellow-400 flex-shrink-0 mt-0.5" />
          <div>
            <h3 className="font-medium text-yellow-400 mb-1">Partial Decompilation</h3>
            <p className="text-sm text-obsidian-400">
              The decompiler was unable to fully analyze this contract.
              The output below may be incomplete or contain errors.
            </p>
          </div>
        </div>
        <pre className="text-xs text-obsidian-400 font-mono bg-obsidian-900/50 p-4 rounded-lg overflow-x-auto whitespace-pre-wrap">
          {decompiledCode}
        </pre>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Auto-decompiled banner */}
      {isAutoGenerated && (
        <div className="flex items-start gap-2.5 p-3 rounded-lg bg-ether-500/5 border border-ether-500/20">
          <Info className="w-4 h-4 text-ether-400 flex-shrink-0 mt-0.5" />
          <p className="text-xs text-obsidian-400">
            Auto-decompiled from bytecode. This is generated pseudocode — variable names
            and some logic may be approximate.
          </p>
        </div>
      )}

      {/* Header with search and actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div className="flex items-center gap-2">
          <span className="text-sm text-obsidian-400">
            {parsed?.functions.length || 0} functions detected
          </span>
          {parsed && parsed.storage.length > 0 && (
            <span className="text-sm text-obsidian-500">
              | {parsed.storage.length} storage variables
            </span>
          )}
        </div>

        <div className="flex items-center gap-2">
          {/* Search */}
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-obsidian-500" />
            <input
              type="text"
              placeholder="Search functions..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-9 pr-3 py-1.5 text-sm bg-obsidian-800 border border-obsidian-700 rounded-lg text-obsidian-200 placeholder:text-obsidian-500 focus:outline-none focus:border-ether-500/50 w-48"
            />
          </div>

          {/* Actions */}
          <button
            onClick={expandAll}
            className="px-2 py-1.5 text-xs text-obsidian-400 hover:text-obsidian-200 transition-colors"
          >
            Expand All
          </button>
          <button
            onClick={collapseAll}
            className="px-2 py-1.5 text-xs text-obsidian-400 hover:text-obsidian-200 transition-colors"
          >
            Collapse All
          </button>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 text-sm bg-obsidian-800 hover:bg-obsidian-700 rounded-lg transition-colors"
          >
            {copied ? (
              <>
                <Check className="w-4 h-4 text-green-400" />
                <span className="text-green-400">Copied</span>
              </>
            ) : (
              <>
                <Copy className="w-4 h-4 text-obsidian-400" />
                <span className="text-obsidian-300">Copy All</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Storage Variables */}
      {parsed && parsed.storage.length > 0 && (
        <div className="rounded-lg border border-obsidian-800 bg-obsidian-900/30 overflow-hidden">
          <div className="px-4 py-2 bg-obsidian-800/50 border-b border-obsidian-800">
            <span className="text-sm font-medium text-obsidian-300">Storage Variables</span>
          </div>
          <div className="p-4">
            <div className="space-y-1 font-mono text-xs">
              {parsed.storage.map((variable, i) => (
                <div key={i} className="text-obsidian-400">
                  <HighlightedCode code={variable} searchQuery={searchQuery} />
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Functions List */}
      <div className="space-y-2">
        {filteredFunctions.map((func) => {
          const key = `${func.name}-${func.originalIndex}`;
          return (
            <FunctionBlock
              key={key}
              func={func}
              isExpanded={expandedFunctions.has(key)}
              onToggle={() => toggleFunction(key)}
              searchQuery={searchQuery}
            />
          );
        })}

        {searchQuery && filteredFunctions.length === 0 && (
          <div className="text-center py-8 text-obsidian-500">
            <Search className="w-8 h-8 mx-auto mb-2 opacity-50" />
            <p>No functions matching &quot;{searchQuery}&quot;</p>
          </div>
        )}
      </div>

      {/* Show full decompiled code toggle */}
      <div className="pt-4 border-t border-obsidian-800">
        <button
          onClick={() => setShowAllCode(!showAllCode)}
          className="flex items-center gap-2 text-sm text-obsidian-500 hover:text-obsidian-300 transition-colors"
        >
          {showAllCode ? (
            <ChevronUp className="w-4 h-4" />
          ) : (
            <ChevronDown className="w-4 h-4" />
          )}
          {showAllCode ? "Hide" : "Show"} full decompiled output
        </button>

        {showAllCode && normalizedCode && (
          <FormattedCodeBlock
            code={normalizedCode}
            format={parsed?.format || "python"}
            searchQuery={searchQuery}
          />
        )}
      </div>
    </div>
  );
}

function FunctionBlock({
  func,
  isExpanded,
  onToggle,
  searchQuery,
}: {
  func: ParsedFunction;
  isExpanded: boolean;
  onToggle: () => void;
  searchQuery: string;
}) {
  return (
    <div className="rounded-lg border border-obsidian-800 bg-obsidian-900/30 overflow-hidden">
      {/* Function header - always visible */}
      <button
        onClick={onToggle}
        className="w-full px-4 py-3 flex items-center justify-between hover:bg-obsidian-800/30 transition-colors"
      >
        <div className="flex items-center gap-3">
          <span className="font-mono text-sm text-ether-400">
            <HighlightedCode code={func.name} searchQuery={searchQuery} />
          </span>
          {func.isPayable && (
            <span className="px-1.5 py-0.5 text-xs bg-green-500/10 text-green-400 rounded">
              payable
            </span>
          )}
          {(func.name === "_fallback" || func.name === "fallback") && (
            <span className="px-1.5 py-0.5 text-xs bg-obsidian-700 text-obsidian-400 rounded">
              default
            </span>
          )}
          {(func.name === "_receive" || func.name === "receive") && (
            <span className="px-1.5 py-0.5 text-xs bg-obsidian-700 text-obsidian-400 rounded">
              receive
            </span>
          )}
        </div>
        {isExpanded ? (
          <ChevronUp className="w-4 h-4 text-obsidian-500" />
        ) : (
          <ChevronDown className="w-4 h-4 text-obsidian-500" />
        )}
      </button>

      {/* Function body - expandable */}
      {isExpanded && (
        <div className="px-4 pb-4 border-t border-obsidian-800">
          <pre className="mt-3 text-xs font-mono text-obsidian-300 overflow-x-auto whitespace-pre-wrap">
            <HighlightedCode code={func.body} searchQuery={searchQuery} />
          </pre>
        </div>
      )}
    </div>
  );
}

// ---------------------------------------------------------------------------
// Syntax-highlighted full code view
// ---------------------------------------------------------------------------

const PYTHON_KEYWORDS = new Set([
  "def", "return", "if", "else", "elif", "while", "for", "not", "and", "or",
  "require", "assert", "revert", "stop", "continue", "log", "call", "static",
  "delegatecall", "selfdestruct", "payable",
]);

const SOLIDITY_KEYWORDS = new Set([
  "function", "return", "returns", "if", "else", "while", "for", "require",
  "revert", "assert", "emit", "contract", "mapping", "address", "uint256",
  "uint8", "uint16", "uint128", "int256", "bool", "bytes", "bytes32", "string",
  "memory", "storage", "calldata", "public", "private", "internal", "external",
  "view", "pure", "payable", "modifier", "event", "struct", "enum",
  "constructor", "fallback", "receive", "true", "false",
]);

function tokenizeLine(
  line: string,
  format: CodeFormat
): { text: string; type: "keyword" | "comment" | "string" | "number" | "type" | "normal" }[] {
  const tokens: { text: string; type: "keyword" | "comment" | "string" | "number" | "type" | "normal" }[] = [];
  const keywords = format === "python" ? PYTHON_KEYWORDS : SOLIDITY_KEYWORDS;

  // Check for full-line comment
  const trimmed = line.trim();
  if (
    (format === "python" && trimmed.startsWith("#")) ||
    (format === "solidity" && (trimmed.startsWith("//") || trimmed.startsWith("*") || trimmed.startsWith("/*")))
  ) {
    tokens.push({ text: line, type: "comment" });
    return tokens;
  }

  // Check for inline comment
  const commentChar = format === "python" ? "#" : "//";
  const commentIdx = line.indexOf(commentChar);

  const codePart = commentIdx >= 0 ? line.substring(0, commentIdx) : line;
  const commentPart = commentIdx >= 0 ? line.substring(commentIdx) : "";

  // Tokenize the code part
  // Match words, numbers (hex and decimal), strings, and everything else
  const regex = /(\b0x[0-9a-fA-F]+\b|\b\d+\b|\b[a-zA-Z_$][a-zA-Z0-9_$]*\b|"[^"]*"|'[^']*'|[^\w\s]|\s+)/g;
  let match;
  let lastIdx = 0;

  while ((match = regex.exec(codePart)) !== null) {
    // Add any gap (shouldn't happen, but safety)
    if (match.index > lastIdx) {
      tokens.push({ text: codePart.slice(lastIdx, match.index), type: "normal" });
    }

    const text = match[0];
    if (text.startsWith('"') || text.startsWith("'")) {
      tokens.push({ text, type: "string" });
    } else if (/^0x[0-9a-fA-F]+$/.test(text) || /^\d+$/.test(text)) {
      tokens.push({ text, type: "number" });
    } else if (keywords.has(text)) {
      tokens.push({ text, type: "keyword" });
    } else if (
      format === "solidity" &&
      /^(uint\d*|int\d*|bytes\d*|address|bool|string)$/.test(text)
    ) {
      tokens.push({ text, type: "type" });
    } else if (
      format === "python" &&
      /^(addr|uint256|uint8|int256|bool|bytes|bytes32|address|mapping|array|struct)$/.test(text)
    ) {
      tokens.push({ text, type: "type" });
    } else {
      tokens.push({ text, type: "normal" });
    }

    lastIdx = match.index + text.length;
  }

  // Remaining code
  if (lastIdx < codePart.length) {
    tokens.push({ text: codePart.slice(lastIdx), type: "normal" });
  }

  // Append comment
  if (commentPart) {
    tokens.push({ text: commentPart, type: "comment" });
  }

  return tokens;
}

const TOKEN_COLORS: Record<string, string> = {
  keyword: "text-purple-400",
  comment: "text-obsidian-600 italic",
  string: "text-green-400",
  number: "text-amber-400",
  type: "text-sky-400",
  normal: "text-obsidian-300",
};

function FormattedCodeBlock({
  code,
  format,
  searchQuery,
}: {
  code: string;
  format: CodeFormat;
  searchQuery: string;
}) {
  const lines = code.split("\n");
  const gutterWidth = String(lines.length).length;

  return (
    <div className="mt-4 rounded-lg border border-obsidian-800 bg-obsidian-950 overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full border-collapse">
          <tbody>
            {lines.map((line, i) => (
              <tr key={i} className="hover:bg-obsidian-900/40 transition-colors">
                <td
                  className="select-none text-right pr-4 pl-4 py-0 text-xs font-mono text-obsidian-700 border-r border-obsidian-800/50 align-top"
                  style={{ minWidth: `${gutterWidth + 2}ch` }}
                >
                  {i + 1}
                </td>
                <td className="pl-4 pr-4 py-0 text-xs font-mono whitespace-pre-wrap break-all">
                  {searchQuery.trim() ? (
                    <HighlightedCode code={line} searchQuery={searchQuery} />
                  ) : (
                    <SyntaxLine tokens={tokenizeLine(line, format)} />
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function SyntaxLine({
  tokens,
}: {
  tokens: { text: string; type: string }[];
}) {
  if (tokens.length === 0) return <span>{"\u00A0"}</span>;
  return (
    <>
      {tokens.map((tok, i) => (
        <span key={i} className={TOKEN_COLORS[tok.type] || TOKEN_COLORS.normal}>
          {tok.text}
        </span>
      ))}
    </>
  );
}

function HighlightedCode({ code, searchQuery }: { code: string; searchQuery: string }) {
  if (!searchQuery.trim()) {
    return <>{code}</>;
  }

  const query = searchQuery.toLowerCase();
  const parts: React.ReactNode[] = [];
  let lastIndex = 0;

  const lowerCode = code.toLowerCase();
  let searchIndex = lowerCode.indexOf(query);

  while (searchIndex !== -1) {
    // Add text before match
    if (searchIndex > lastIndex) {
      parts.push(code.slice(lastIndex, searchIndex));
    }

    // Add highlighted match
    parts.push(
      <span key={searchIndex} className="bg-yellow-500/30 text-yellow-200 rounded px-0.5">
        {code.slice(searchIndex, searchIndex + query.length)}
      </span>
    );

    lastIndex = searchIndex + query.length;
    searchIndex = lowerCode.indexOf(query, lastIndex);
  }

  // Add remaining text
  if (lastIndex < code.length) {
    parts.push(code.slice(lastIndex));
  }

  return <>{parts}</>;
}
