/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface EthereumHistoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getHistoryHash"
      | "hasHistory"
      | "historyHashes"
      | "publishHistory"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "HistoryPublished"): EventFragment;

  encodeFunctionData(
    functionFragment: "getHistoryHash",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "historyHashes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishHistory",
    values: [AddressLike, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getHistoryHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasHistory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "historyHashes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishHistory",
    data: BytesLike
  ): Result;
}

export namespace HistoryPublishedEvent {
  export type InputTuple = [
    contractAddress: AddressLike,
    contentHash: BytesLike,
    timestamp: BigNumberish,
    contentJson: string
  ];
  export type OutputTuple = [
    contractAddress: string,
    contentHash: string,
    timestamp: bigint,
    contentJson: string
  ];
  export interface OutputObject {
    contractAddress: string;
    contentHash: string;
    timestamp: bigint;
    contentJson: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EthereumHistory extends BaseContract {
  connect(runner?: ContractRunner | null): EthereumHistory;
  waitForDeployment(): Promise<this>;

  interface: EthereumHistoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getHistoryHash: TypedContractMethod<
    [contractAddress: AddressLike],
    [string],
    "view"
  >;

  hasHistory: TypedContractMethod<
    [contractAddress: AddressLike],
    [boolean],
    "view"
  >;

  historyHashes: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  publishHistory: TypedContractMethod<
    [contractAddress: AddressLike, contentHash: BytesLike, contentJson: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getHistoryHash"
  ): TypedContractMethod<[contractAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "hasHistory"
  ): TypedContractMethod<[contractAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "historyHashes"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "publishHistory"
  ): TypedContractMethod<
    [contractAddress: AddressLike, contentHash: BytesLike, contentJson: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "HistoryPublished"
  ): TypedContractEvent<
    HistoryPublishedEvent.InputTuple,
    HistoryPublishedEvent.OutputTuple,
    HistoryPublishedEvent.OutputObject
  >;

  filters: {
    "HistoryPublished(address,bytes32,uint256,string)": TypedContractEvent<
      HistoryPublishedEvent.InputTuple,
      HistoryPublishedEvent.OutputTuple,
      HistoryPublishedEvent.OutputObject
    >;
    HistoryPublished: TypedContractEvent<
      HistoryPublishedEvent.InputTuple,
      HistoryPublishedEvent.OutputTuple,
      HistoryPublishedEvent.OutputObject
    >;
  };
}
