import type { Metadata } from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { fetchDonations, getEnsName, shortAddress } from "@/lib/donations";
import { getDb } from "@/lib/db-client";
import { donationClaims } from "@/lib/schema";
import { inArray } from "drizzle-orm";
import { formatEther } from "viem";
import { ClaimButton } from "./SupportersClient";

export const metadata: Metadata = {
  title: "Supporters - Ethereum History",
  description:
    "The people who keep Ethereum History running. View our donors and support the free, open archive.",
};

// Revalidate every 5 minutes
export const revalidate = 300;

const HISTORY_TOKEN = "0xD67A9266D0ae84839f62197713B2D2A9f3a62Ba3";
const HISTORY_FEE_SENDER = "0xdbd69cb44135a96474de7d28a6e4cbfc2aacef7f";
const WMEAT_ADDRESS = "0xDFA208bb0b811cFbb5fA3ea98EC37AA86180E668";
const WMEAT_POOL_MAINNET = "0xC3b9903F07c7B7614B9b5B490c7cE89bd688282E";
const WMEAT_POOL_BASE = "0xb9Ce62Df766fFC0BB0d5D530e2DDe32eC3Baa578";
const DONATION_WALLET_ADDRESS = "0x123bf3b32fB3986C9251C81430d2542D5054F0d2";
const ETHERSCAN_API_KEY = "AHMV3WAI75TQVJI2XEFUUKFKK1KJTFY1BD";

async function fetchHistoryFeesEth(): Promise<number> {
  // L1: internal txs from the HISTORY fee distributor contract
  const l1Promise = (async () => {
    try {
      const url =
        `https://api.etherscan.io/v2/api?chainid=1&module=account&action=txlistinternal` +
        `&address=${DONATION_WALLET_ADDRESS}&sort=asc&apikey=${ETHERSCAN_API_KEY}`;
      const res = await fetch(url, { cache: "no-store" });
      const json = await res.json();
      if (json.status !== "1" || !Array.isArray(json.result)) return 0;
      const total = json.result
        .filter((tx: Record<string, string>) =>
          tx.to?.toLowerCase() === DONATION_WALLET_ADDRESS.toLowerCase() &&
          tx.from?.toLowerCase() === HISTORY_FEE_SENDER.toLowerCase() &&
          tx.value !== "0" &&
          tx.isError === "0"
        )
        .reduce((sum: bigint, tx: Record<string, string>) => sum + BigInt(tx.value), BigInt(0));
      return Number(formatEther(total));
    } catch { return 0; }
  })();

  // Base: WETH transfers from the Doppler pool contract (fee claims)
  const DOPPLER_POOL = "0xd59ce43e53d69f190e15d9822fb4540dccc91178";
  const basePromise = (async () => {
    const baseRpcUrl = process.env.BASE_RPC_URL;
    if (!baseRpcUrl) return 0;
    try {
      const res = await fetch(baseRpcUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          jsonrpc: "2.0",
          method: "alchemy_getAssetTransfers",
          params: [{
            toAddress: DONATION_WALLET_ADDRESS,
            fromAddress: DOPPLER_POOL,
            category: ["erc20"],
            withMetadata: false,
            excludeZeroValue: true,
            maxCount: "0x64",
            order: "desc",
          }],
          id: 1,
        }),
        cache: "no-store",
      });
      const json = await res.json();
      const transfers: Record<string, unknown>[] = json?.result?.transfers ?? [];
      return transfers
        .filter((t) => t.asset === "WETH")
        .reduce((sum, t) => sum + parseFloat(String(t.value ?? 0)), 0);
    } catch { return 0; }
  })();

  const [l1, base] = await Promise.all([l1Promise, basePromise]);
  return l1 + base;
}

/**
 * Estimate total WETH fees generated by the w🍖 Uniswap V3 pools (mainnet + Base).
 * Fees accrue in the pool and have not been collected yet.
 * Computes 1% of total swap volume from on-chain Swap events.
 */
async function fetchWmeatFeesEth(): Promise<number> {
  const FEE_TIER = 0.01; // 1% fee tier

  // Mainnet: sum absolute WETH amounts from all Swap events
  const mainnetPromise = (async (): Promise<number> => {
    try {
      const SWAP_TOPIC = "0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67";
      const url =
        `https://api.etherscan.io/v2/api?chainid=1&module=logs&action=getLogs` +
        `&address=${WMEAT_POOL_MAINNET}&topic0=${SWAP_TOPIC}&fromBlock=0&toBlock=latest` +
        `&apikey=${ETHERSCAN_API_KEY}`;
      const res = await fetch(url, { cache: "no-store" });
      const json = await res.json();
      const logs: Record<string, string>[] = Array.isArray(json.result) ? json.result : [];
      let totalWeth = BigInt(0);
      for (const log of logs) {
        const data = (log.data || "0x").slice(2);
        if (data.length >= 64) {
          let a0 = BigInt("0x" + data.slice(0, 64));
          if (a0 >= BigInt(2) ** BigInt(255)) a0 -= BigInt(2) ** BigInt(256);
          totalWeth += a0 < 0n ? -a0 : a0;
        }
      }
      return Number(formatEther(totalWeth)) * FEE_TIER;
    } catch { return 0; }
  })();

  // Base: use GeckoTerminal for volume data
  const basePromise = (async (): Promise<number> => {
    try {
      const res = await fetch(
        `https://api.geckoterminal.com/api/v2/networks/base/pools/${WMEAT_POOL_BASE}`,
        { headers: { Accept: "application/json", "User-Agent": "EthereumHistory/1.0" }, next: { revalidate: 3600 } }
      );
      const json = await res.json();
      const vol24h = parseFloat(json?.data?.attributes?.volume_usd?.h24 ?? "0");
      const ethPrice = 2000;
      return (vol24h / ethPrice) * FEE_TIER;
    } catch { return 0; }
  })();

  const [mainnet, base] = await Promise.all([mainnetPromise, basePromise]);
  return mainnet + base;
}

type Tier = "philanthropist" | "benefactor" | "sponsor" | "patron" | "supporter";

function getTier(ethAmount: number): Tier {
  if (ethAmount >= 1.0) return "philanthropist";
  if (ethAmount >= 0.1) return "benefactor";
  if (ethAmount >= 0.05) return "sponsor";
  if (ethAmount >= 0.01) return "patron";
  return "supporter";
}

const TIER_CONFIG: Record<Tier, { label: string; color: string; bg: string; border: string; threshold: string }> = {
  philanthropist: {
    label: "Philanthropist",
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
    border: "border-yellow-400/30",
    threshold: "1.0+ ETH",
  },
  benefactor: {
    label: "Benefactor",
    color: "text-ether-300",
    bg: "bg-ether-500/10",
    border: "border-ether-500/30",
    threshold: "0.1+ ETH",
  },
  sponsor: {
    label: "Sponsor",
    color: "text-obsidian-200",
    bg: "bg-obsidian-700/30",
    border: "border-obsidian-500/30",
    threshold: "0.05+ ETH",
  },
  patron: {
    label: "Patron",
    color: "text-obsidian-400",
    bg: "bg-obsidian-800/40",
    border: "border-obsidian-600/30",
    threshold: "0.01+ ETH",
  },
  supporter: {
    label: "Supporter",
    color: "text-obsidian-500",
    bg: "bg-obsidian-900/40",
    border: "border-obsidian-700/30",
    threshold: "any amount",
  },
};

interface DonationRow {
  txHash: string;
  from: string;
  ethAmount: number;
  tokenSymbol: "ETH" | "USDC";
  tokenAmount: string;
  timestamp: number;
  displayName: string;
  note: string | null;
  isClaimed: boolean;
  tier: Tier;
  isFounding: boolean;
  chain: "ethereum" | "base";
}

async function getDonationData(): Promise<{
  donations: DonationRow[];
  totalEth: string;
  donorCount: number;
}> {
  const txs = await fetchDonations();

  if (txs.length === 0) {
    return { donations: [], totalEth: "0.0000", donorCount: 0 };
  }

  // Fetch claims from DB
  let claimsMap: Record<string, { displayName: string; note: string | null }> = {};
  try {
    const db = getDb();
    const txHashes = txs.map((t) => t.txHash);
    const claims = await db
      .select()
      .from(donationClaims)
      .where(inArray(donationClaims.txHash, txHashes));
    claimsMap = Object.fromEntries(
      claims.map((c) => [c.txHash, { displayName: c.displayName, note: c.note }])
    );
  } catch (err) {
    console.warn("[supporters page] DB not available:", err);
  }

  // Resolve ENS for unclaimed addresses (best effort, capped)
  const ensMap: Record<string, string | null> = {};
  const unclaimedAddresses = [
    ...new Set(txs.filter((t) => !claimsMap[t.txHash]).map((t) => t.from)),
  ].slice(0, 20);

  await Promise.allSettled(
    unclaimedAddresses.map(async (addr) => {
      const name = await getEnsName(addr);
      ensMap[addr] = name;
    })
  );

  // Aggregate by donor address
  const byAddress = new Map<string, {
    from: string;
    totalEthWei: bigint;
    totalUsdc: number;
    firstTimestamp: number;
    latestTxHash: string;
    isClaimed: boolean;
    chain: "ethereum" | "base";
  }>();

  for (const tx of txs) {
    const key = tx.from.toLowerCase();
    const existing = byAddress.get(key);
    const ethWei = tx.tokenSymbol === "ETH" ? BigInt(tx.valueWei) : BigInt(0);
    const usdc = tx.tokenSymbol === "USDC" ? parseFloat(tx.tokenAmount) : 0;
    const claimed = !!claimsMap[tx.txHash];
    if (!existing) {
      byAddress.set(key, {
        from: tx.from,
        totalEthWei: ethWei,
        totalUsdc: usdc,
        firstTimestamp: tx.timestamp,
        latestTxHash: tx.txHash,
        isClaimed: claimed,
        chain: tx.chain,
      });
    } else {
      existing.totalEthWei += ethWei;
      existing.totalUsdc += usdc;
      if (tx.timestamp < existing.firstTimestamp) existing.firstTimestamp = tx.timestamp;
      if (claimed) existing.isClaimed = true;
    }
  }

  // Determine founding supporters: first 10 unique donor addresses by first tx
  const sortedByFirst = [...byAddress.values()].sort((a, b) => a.firstTimestamp - b.firstTimestamp);
  const foundingAddresses = new Set(sortedByFirst.slice(0, 10).map((d) => d.from.toLowerCase()));

  // Build rows (one per address)
  const rows: DonationRow[] = [...byAddress.values()].map((d) => {
    const claim = Object.values(claimsMap).find((_, i) =>
      Object.keys(claimsMap)[i] && txs.find((t) => t.from.toLowerCase() === d.from.toLowerCase() && claimsMap[t.txHash])
    );
    // Find any claim for this address
    const addressClaim = txs
      .filter((t) => t.from.toLowerCase() === d.from.toLowerCase() && claimsMap[t.txHash])
      .map((t) => claimsMap[t.txHash])[0];

    const ens = ensMap[d.from] ?? null;
    const ethAmount = parseFloat(formatEther(d.totalEthWei));
    return {
      txHash: d.latestTxHash,
      from: d.from,
      ethAmount,
      tokenSymbol: ethAmount > 0 ? "ETH" : "USDC",
      tokenAmount: ethAmount > 0 ? ethAmount.toFixed(4) : d.totalUsdc.toFixed(2),
      timestamp: d.firstTimestamp,
      displayName: addressClaim?.displayName ?? ens ?? shortAddress(d.from),
      note: addressClaim?.note ?? null,
      isClaimed: d.isClaimed,
      tier: getTier(ethAmount),
      isFounding: foundingAddresses.has(d.from.toLowerCase()),
      chain: d.chain,
    };
  });

  // Sort by ETH amount descending
  rows.sort((a, b) => b.ethAmount - a.ethAmount || a.timestamp - b.timestamp);

  // Total ETH across all txs
  const totalEthWei = txs
    .filter((t) => t.tokenSymbol === "ETH")
    .reduce((sum, t) => sum + BigInt(t.valueWei), BigInt(0));

  const uniqueDonors = byAddress.size;

  return {
    donations: rows,
    totalEth: parseFloat(formatEther(totalEthWei)).toFixed(4),
    donorCount: uniqueDonors,
  };
}

function formatDate(timestamp: number): string {
  return new Date(timestamp * 1000).toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
}

export default async function SupportersPage() {
  const [{ donations, totalEth, donorCount }, historyFeesEth, wmeatFeesEth] = await Promise.all([
    getDonationData(),
    fetchHistoryFeesEth(),
    fetchWmeatFeesEth(),
  ]);

  return (
    <div className="min-h-screen bg-obsidian-950">
      <Header />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        {/* Hero */}
        <div className="text-center mb-12">
          <h1 className="text-4xl sm:text-5xl font-bold text-obsidian-50 mb-4">
            Supporters
          </h1>
          <p className="text-obsidian-400 text-lg max-w-xl mx-auto leading-relaxed mb-8">
            These donors keep EthereumHistory running. No ads. No paywalls. Just people who believe the history of Ethereum is worth preserving.
          </p>

          {/* Stats */}
          <div className="inline-grid grid-cols-2 gap-px bg-obsidian-800 rounded-2xl overflow-hidden border border-obsidian-800">
            <div className="bg-obsidian-950 px-8 py-5">
              <p className="text-3xl font-bold text-ether-400">{totalEth} ETH</p>
              <p className="text-xs text-obsidian-600 uppercase tracking-widest mt-1">Total donated</p>
            </div>
            <div className="bg-obsidian-950 px-8 py-5">
              <p className="text-3xl font-bold text-obsidian-100">{donorCount}</p>
              <p className="text-xs text-obsidian-600 uppercase tracking-widest mt-1">Unique donors</p>
            </div>
          </div>
        </div>

        {/* Token fee trackers */}
        <div className="mb-10 space-y-3">
            {historyFeesEth > 0 && (
              <div className="rounded-2xl border border-obsidian-700 bg-obsidian-900/50 px-5 py-4">
                <div className="flex items-center justify-between gap-4">
                  <div>
                    <span className="text-sm font-semibold text-obsidian-100">HISTORY Token</span>
                    <p className="text-xs text-obsidian-500 mt-0.5">
                      Created by a supporter on{" "}
                      <a
                        href={`https://dexscreener.com/base/${HISTORY_TOKEN}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="hover:text-ether-400 transition-colors"
                      >
                        Base ↗
                      </a>
                      {" "}- 1% of trading fees support this archive
                    </p>
                  </div>
                  <span className="text-sm font-semibold text-ether-300 shrink-0">
                    {historyFeesEth.toFixed(4)} ETH
                  </span>
                </div>
              </div>
            )}
            <div className="rounded-2xl border border-obsidian-700 bg-obsidian-900/50 px-5 py-4">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <span className="text-sm font-semibold text-obsidian-100">
                      Wrapped Unicorn Meat (w🍖)
                    </span>
                    <a
                      href={`https://ethereumhistory.com/contract/${WMEAT_ADDRESS}`}
                      className="text-xs text-obsidian-600 hover:text-ether-400 transition-colors font-mono"
                    >
                      {WMEAT_ADDRESS.slice(0, 10)}...
                    </a>
                  </div>
                  <p className="text-xs text-obsidian-500 mt-1 leading-relaxed">
                    A historic ERC-20 token tracing back to 2016 - created by grinding Unicorns through{" "}
                    <a
                      href="https://unicornmeateth.com/grinder-association"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="hover:text-ether-400 transition-colors"
                    >
                      avsa&apos;s grinder contract ↗
                    </a>
                    . 1% of trading fees from both pools supports this archive.
                  </p>
                  <div className="flex flex-wrap items-center gap-3 mt-2">
                    <a
                      href={`https://app.uniswap.org/explore/pools/ethereum/${WMEAT_POOL_MAINNET}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs text-obsidian-600 hover:text-ether-400 transition-colors"
                    >
                      Uniswap Mainnet ↗
                    </a>
                    <span className="text-obsidian-800 text-xs">|</span>
                    <a
                      href={`https://app.uniswap.org/explore/pools/base/${WMEAT_POOL_BASE}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs text-obsidian-600 hover:text-ether-400 transition-colors"
                    >
                      Uniswap Base ↗
                    </a>
                    <span className="text-obsidian-800 text-xs">|</span>
                    <a
                      href="https://unicornmeateth.com"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs text-obsidian-600 hover:text-ether-400 transition-colors"
                    >
                      unicornmeateth.com ↗
                    </a>
                  </div>
                </div>
                <div className="shrink-0 text-right">
                  <span className="text-sm font-semibold text-ether-300">
                    {wmeatFeesEth > 0 ? ("~" + wmeatFeesEth.toFixed(4) + " ETH") : "calculating..."}
                  </span>
                  <p className="text-xs text-obsidian-700 mt-0.5">
                    {wmeatFeesEth > 0 ? "estimated from swap volume" : "fees accumulating"}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Tier legend */}
        <div className="flex flex-wrap items-center gap-3 mb-8 justify-center">
          {(["philanthropist", "benefactor", "sponsor", "patron", "supporter"] as Tier[]).map((tier) => {
            const cfg = TIER_CONFIG[tier];
            return (
              <span
                key={tier}
                className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium border ${cfg.bg} ${cfg.color} ${cfg.border}`}
              >
                <TierDot tier={tier} />
                {cfg.label}
                <span className="text-obsidian-600 font-normal">{cfg.threshold}</span>
              </span>
            );
          })}
          <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-medium border bg-ether-500/10 text-ether-400 border-ether-500/30">
            Founding Supporter: first 10 donors
          </span>
        </div>

        {/* Leaderboard */}
        {donations.length === 0 ? (
          <div className="text-center py-20 text-obsidian-600">
            No donations yet. Be the first!
          </div>
        ) : (
          <div className="space-y-3 mb-16">
            {donations.map((d, idx) => (
              <DonationCard key={d.txHash} donation={d} rank={idx + 1} />
            ))}
          </div>
        )}

        {/* Claim section */}
        <div className="border-t border-obsidian-800 pt-12 text-center">
          <h2 className="text-2xl font-bold text-obsidian-100 mb-3">
            Did you donate?
          </h2>
          <p className="text-obsidian-400 mb-6 max-w-md mx-auto">
            Sign a message with your wallet to claim your donation and add your name to the log.
          </p>
          <ClaimButton />
          <p className="text-xs text-obsidian-700 mt-4">
            Signing is free. No gas required.
          </p>
        </div>
      </main>
    </div>
  );
}

function TierDot({ tier }: { tier: Tier }) {
  const colors: Record<Tier, string> = {
    philanthropist: "bg-yellow-400",
    benefactor: "bg-ether-300",
    sponsor: "bg-obsidian-200",
    patron: "bg-obsidian-400",
    supporter: "bg-obsidian-600",
  };
  return <span className={`w-1.5 h-1.5 rounded-full ${colors[tier]}`} />;
}

function DonationCard({ donation: d, rank }: { donation: DonationRow; rank: number }) {
  const cfg = TIER_CONFIG[d.tier];
  const date = formatDate(d.timestamp);
  const explorerUrl = d.chain === "base"
    ? `https://basescan.org/tx/${d.txHash}`
    : `https://etherscan.io/tx/${d.txHash}`;

  return (
    <div className="flex items-start gap-4 p-4 sm:p-5 rounded-2xl bg-obsidian-900/50 border border-obsidian-800 hover:border-obsidian-700 transition-colors">
      {/* Rank */}
      <div className="shrink-0 w-8 text-center">
        <span className="text-lg font-bold text-obsidian-700">{rank}</span>
      </div>

      {/* Main info */}
      <div className="flex-1 min-w-0">
        <div className="flex flex-wrap items-center gap-2 mb-1">
          <span className="font-semibold text-obsidian-100 truncate">{d.displayName}</span>
          {/* Tier badge */}
          <span
            className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium border ${cfg.bg} ${cfg.color} ${cfg.border}`}
          >
            <TierDot tier={d.tier} />
            {cfg.label}
          </span>
          {/* Founding badge */}
          {d.isFounding && (
            <span className="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium bg-ether-500/10 text-ether-400 border border-ether-500/30">
              Founding Supporter
            </span>
          )}

        </div>

        {d.note && (
          <p className="text-sm text-obsidian-500 mt-1 italic">&ldquo;{d.note}&rdquo;</p>
        )}

        <div className="flex flex-wrap items-center gap-3 mt-2">
          <span className="text-xs text-obsidian-600">{date}</span>
          <a
            href={explorerUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-obsidian-700 hover:text-ether-400 transition-colors font-mono"
          >
            {d.txHash.slice(0, 10)}...
          </a>
        </div>
      </div>

      {/* Amount */}
      <div className="shrink-0 text-right">
        <p className="font-semibold text-obsidian-100">
          {d.tokenSymbol === "ETH"
            ? `${parseFloat(d.tokenAmount).toFixed(4)} ETH`
            : `${d.tokenAmount} USDC`}
        </p>
        {d.isClaimed && (
          <p className="text-xs text-ether-600 mt-0.5">Claimed</p>
        )}
      </div>
    </div>
  );
}
